### ISSUE TITLE
ステートの命名について

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_Recoil_State#3]
```
const [useImage, setUserImage] = useState({ data: { sprites: {} } })

const [useJson, setUseJson] = useState(null)
```
あたりの命名気になったのでコメントいたします〜

カスタムフック自体の命名は慣習に倣って「useXXX」のように命名しますが、ステートに対して「use」のプリフィックスは適切でないように感じます👀

変数の命名から、どのような情報が格納されているか？が分かりやすいような命名を考えてみると良いと思います〜

ここら辺の記事とか読んでみると勉強になりそうです〜
https://qiita.com/Ted-HM/items/7dde25dcffae4cdc7923#%E5%BC%8F%E5%80%A4%E5%A4%89%E6%95%B0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by macmeals** [comment]
以下の様に変更しました👍
`const [useImage, setUserImage] = useState({ data: { sprites: {} } })
　　　　↓
const [apiImage, setApiImage] = useState({ data: { sprites: {} } })

const [useJson, setUseJson] = useState(null)
　　　　↓
 const [apiJson, setApiJson] = useState(null)

`
それぞれApiの画像URL、APIのテキストを取得してきているので、そのように変更しました。

**Comment by mizushima1226** [comment]
変更はどのブランチにpushしましたでしょうか？
変更内容が確認できず。。。🙇‍♂️

じゃけぇさんのコメントでいくと
>このフックの役割は画像パスを取得することだと思うので、Stateにresponseを全て持たせるのではなく、対象の画像のパスのみこのカスタムフック内で取り出してStateに設定しreturnしてあげたほうが良いです（コンポーネント側はカスタムフックから返却されたSateをurlに設定するだけで良くなる）

apiImageは文字列になると思います
初期値は空文字で良さそうです〜
apiImageより、単にimageやimagePathなどで良いかと思います

apiJsonだと、まずこのステートにセットされる値がjson文字列ではないと思うのでチグハグになってしまいます👀
受け取るデータはどのようなオブジェクトでしょうか？受け取るオブジェクトに対してわかりやすい名前をつけてあげると良いと思います
todoのリストであれば`todos`や`todoList`などですね〜

**Comment by macmeals** [comment]
こちらもブランチが分かり難く申し訳ありません・・・🙇‍♂️。全てのIssueの対応を行ない、MainブランチにPushしていますのでMainブランチをご確認頂ければと思います。

主にuseImageGet.js、useTextGet.jsのstate等を修正しています。

→useImageGet.jsは以下の通り修正したのですが、以下分かりづらそうでしょうか？？
const [apiPokemonfront, setApiPokemonfront] = useState("") // →前面画像のURLのstate管理
const [apiPokemonBack, setApiPokemonBack] = useState("") // →背面画像のURLのstate管理

→useTextGet.js　は以下の通り修正しました🙇‍♂️
const [textTitle, setTextTitle] = useState("")

**Comment by mizushima1226** [comment]
OKと思います〜👍
