### ISSUE TITLE
ディレクトリ構成について

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_Recoil_State#4]
`src/component`ディレクトリを切っていますが、`src/atoms`を`component`の直下に配置するのが良いと思います〜

**Comment by mizushima1226** [comment]
あ、失礼しました。
`src/atoms`は`recoil`の方でしたね。。。
`atomic design`のatomsと混乱してました🙏

`src/store`とすると伝わりやすいかもです〜
そういうディレクトリ名もあるんだなぁ程度に思っていただければ良いです👍

このコメント確認いただけたらそのままこのissueをcloseしていただいてOKです👍

**Comment by macmeals** [comment]
コメントありがとうございます。承知しました！👍
