### ISSUE TITLE
グローバルステートに関するロジックをカスタムフック化する

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_Recoil_State#5]
`TodoListAtom`を画面コンポーネントで直接参照する実装になっているかと思います。

useTodoのようなカスタムフックからのみ`TodoListAtom`を参照するようにし、
Todoに関するロジックをカスタムフック内に隠蔽・カスタムフックはステートとTodoに関する操作を提供するような実装にすると良いかと思います👍

実務ではよくある実装かと思いますので良い練習になりそうです👍

**Comment by macmeals** [comment]
今回Recoilのstate管理を組み合わせて、以下HookにTodoに関する処理をまとめました👍
　useAddtodoAtom.js 　　→Todo登録に関する処理（Todo内容、開始時期、終了時期を取得する処理）
　useCompleteTodoAtom.js　→Todo完了に関する処理
　useDeleteTodoAtom.js　　　→Todo削除に関する処理

**Comment by mizushima1226** [comment]
ナイスです👍
