### ISSUE TITLE
TodoListProviderについて

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_Recoil_State#6]
Context APIの実装は別のリポジトリに分けたものと認識してます〜
おそらく分た際にゴミとしてこのリポジトリに残ってしまったものと想像してます
いつか見返すようなことがあった時、混乱の元となるので今のうちに削除しておくのが良さそうです👍

**Comment by macmeals** [comment]
TodoListProviderのフォルダとその配下のファイルを削除しました😁

**Comment by mizushima1226** [comment]
変更確認できずです🙇‍♂️
pushしたブランチを教えてください🙇‍♂️

**Comment by macmeals** [comment]
分かり難く申し訳ありません🙇‍♂️
他のIssue合わせて全て修正して、mainブランチにPushしました。
なので、mainブランチをご確認頂けますでしょうか？？

**Comment by mizushima1226** [comment]
確認できました〜
